version: '3.8'

services:
  web:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=dev_secret_key_replace_in_production
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=health_db
      - DB_USER=health_user
      - DB_PASSWORD=health_password
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
    restart: always

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=health_db
      - POSTGRES_USER=health_user
      - POSTGRES_PASSWORD=health_password
    restart: always

volumes:
  postgres_data: