# k8s/django-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
stringData:
  DOCTOR_DEFAULT_PASSWORD: "test123pass"
  DJANGO_SUPERUSER_EMAIL: "admin@hospital.com"
  DJANGO_SUPERUSER_PASSWORD: "admin123pass"
  SECRET_KEY: "your-secret-key-here"
  DATABASE_URL: "postgresql://user:password@postgres:5432/healthdb"