apiVersion: v1
kind: Secret
metadata:
  name: health-db-secrets
type: Opaque
data:
  # Base64 encoded values - for actual deployment, replace with real secrets
  # Example: echo -n "health_db" | base64
  username: aGVhbHRoX3VzZXI=  # health_user
  password: aGVhbHRoX3Bhc3N3b3Jk  # health_password
  dbname: aGVhbHRoX2Ri  # health_db
---
apiVersion: v1
kind: Secret
metadata:
  name: health-app-secrets
type: Opaque
data:
  # Base64 encoded values - for actual deployment, replace with real secrets
  django-secret-key: ZGphbmdvLWluc2VjdXJlLWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  email-password: ZW1haWwtcGFzc3dvcmQtaGVyZQ==